apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: v7-commerce-cart-app-service
  description: v7 commerce-cart-app-service
  annotations:
    github.com/project-slug: priyankaajbhagatt-collab/v7-commerce-cart-app-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/priyankaajbhagatt-collab/v7-commerce-cart-app-service
    aws.amazon.com/aws-codepipeline-tags: Service=v7-commerce-cart-app-service
    amway.io/markets: mys,tw,sg,tha,latam,can
    amway.io/envs: dev,qa
    amway.io/dev-url: https://v7-commerce-cart-app-service.dev.amway.io
    amway.io/qa-url: https://v7-commerce-cart-app-service.qa.amway.io
    amway.io/slack-channel: v7-commerce-cart-app-service-alerts
  links:
    - title: GitHub repository
      url: https://github.com/priyankaajbhagatt-collab/v7-commerce-cart-app-service
      icon: github
    - title: Open PRs
      url: https://github.com/priyankaajbhagatt-collab/v7-commerce-cart-app-service/pulls
      icon: github

    - title: CodePipeline (MYS)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-mys-main/view?region=us-east-1
      icon: dashboard

    - title: CodePipeline (TW)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-tw-main/view?region=us-east-1
      icon: dashboard

    - title: CodePipeline (SG)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-sg-main/view?region=us-east-1
      icon: dashboard

    - title: CodePipeline (THA)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-tha-main/view?region=us-east-1
      icon: dashboard

    - title: CodePipeline (LATAM)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-latam-main/view?region=us-east-1
      icon: dashboard

    - title: CodePipeline (CAN)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-can-main/view?region=us-east-1
      icon: dashboard

  tags:
    - apac
spec:
  type: service
  lifecycle: production
  owner: group:default/platform
  system: commerce-cart
