apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: v7-commerce-cart-app-service
  description: v7 commerce-cart-app-service
  annotations:
    github.com/project-slug: priyankaajbhagatt-collab/v7-commerce-cart-app-service
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: app=v7-commerce-cart-app-service
    backstage.io/source-location: url:https://github.com/priyankaajbhagatt-collab/v7-commerce-cart-app-service
    argocd/app-selector: service=v7-commerce-cart-app-service
    amway.io/markets: mys,tw,sg
    amway.io/envs: dev,qa,uat,prod
    aws.amazon.com/aws-codepipeline-tags: Service=v7-commerce-cart-app-service
  links:
    - title: GitHub repository
      url: https://github.com/priyankaajbhagatt-collab/v7-commerce-cart-app-service
      icon: github
    - title: Open PRs
      url: https://github.com/priyankaajbhagatt-collab/v7-commerce-cart-app-service/pulls
      icon: github
    - title: Slack — #commerce-cart-general
      url: https://slack.com/app_redirect?channel=commerce-cart-general
      icon: chat
    - title: Slack — #commerce-cart-approval
      url: https://slack.com/app_redirect?channel=commerce-cart-approval
      icon: chat
    - title: CodePipeline (us-east-1)
      url: https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/v7-commerce-cart-app-service-us-east-1-main/view?region=us-east-1
      icon: dashboard
    - title: ArgoCD — dev/us-east-1
      url: https://argocd.dep.altimetrik.io/applications/v7-commerce-cart-app-service-dev-us-east-1
      icon: cloud
    - title: ArgoCD — qa/us-east-1
      url: https://argocd.dep.altimetrik.io/applications/v7-commerce-cart-app-service-qa-us-east-1
      icon: cloud
    - title: ArgoCD — uat/us-east-1
      url: https://argocd.dep.altimetrik.io/applications/v7-commerce-cart-app-service-uat-us-east-1
      icon: cloud
    - title: ArgoCD — prod/us-east-1
      url: https://argocd.dep.altimetrik.io/applications/v7-commerce-cart-app-service-prod-us-east-1
      icon: cloud
    - title: ECR repo (us-east-1)
      url: https://us-east-1.console.aws.amazon.com/ecr/repositories/private/v7-commerce-cart-app-service?region=us-east-1
      icon: docs
    - title: CloudWatch logs (us-east-1)
      url: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/%2Faws%2Fecs%2Fv7-commerce-cart-app-service
      icon: docs
  tags:
    - fastify
    - api
    - commerce
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform
  system: commerce-cart
